<?php
namespace Information;

/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


class DomeResultPage {
  static $_TSPEC;

  public $Bpage = 1;
  public $BpageCount = 0;
  public $Bcount = 0;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'Bpage',
          'type' => TType::I32,
          ),
        2 => array(
          'var' => 'BpageCount',
          'type' => TType::I32,
          ),
        3 => array(
          'var' => 'Bcount',
          'type' => TType::I32,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['Bpage'])) {
        $this->Bpage = $vals['Bpage'];
      }
      if (isset($vals['BpageCount'])) {
        $this->BpageCount = $vals['BpageCount'];
      }
      if (isset($vals['Bcount'])) {
        $this->Bcount = $vals['Bcount'];
      }
    }
  }

  public function getName() {
    return 'DomeResultPage';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->Bpage);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->BpageCount);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 3:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->Bcount);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('DomeResultPage');
    if ($this->Bpage !== null) {
      $xfer += $output->writeFieldBegin('Bpage', TType::I32, 1);
      $xfer += $output->writeI32($this->Bpage);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->BpageCount !== null) {
      $xfer += $output->writeFieldBegin('BpageCount', TType::I32, 2);
      $xfer += $output->writeI32($this->BpageCount);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->Bcount !== null) {
      $xfer += $output->writeFieldBegin('Bcount', TType::I32, 3);
      $xfer += $output->writeI32($this->Bcount);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}


